modLoader="javafml"

loaderVersion="[40,)"

license="Creative Commons Non-Commercial"

[[mods]]

modId="creeperbackguard"

version="1.3.1"

displayName="Creeper Backguard"

displayURL="https://www.curseforge.com/minecraft/mc-mods/creeper-backguard/"

logoFile="icon.png"

authors="JuaanP"

description='''
Make Creepers ignite only within your field of view.
 

Are you tired of losing all your precious items because of those sneaky Creepers that always catch you off guard?

This mod is specifically designed for those who despise losing everything due to Creepers that seemingly appear out of nowhere. With Creeper Backguard, you can finally put an end to those frustrating moments and enjoy a worry-free Minecraft experience.
'''

[[dependencies.creeperbackguard]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.creeperbackguard]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.21)"
    ordering="NONE"
    side="BOTH"
